name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go 1.19
        uses: actions/setup-go@v6
        with:
          go-version: '1.19'

      - name: Tidy modules
        run: go mod tidy

      - name: Run tests with coverage (100% enforced)
        run: make test
