name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Go 1.19
        uses: actions/setup-go@v6
        with:
          go-version: '1.19'

      - name: Tidy modules
        run: go mod tidy

      - name: Run tests with coverage (100% enforced)
        run: make test

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.out
          flags: unittests
          fail_ci_if_error: true
